plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    //Spring
    implementation 'org.springframework.boot:spring-boot-starter-hateoas:3.5.4'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.5.4'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.5.4'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    //security
    implementation 'org.springframework.boot:spring-boot-starter-security:3.5.4'
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.5.4'
    implementation("io.jsonwebtoken:jjwt-api:0.12.6")

    implementation 'org.springframework.security:spring-security-core:6.5.3'
    implementation 'org.springframework.security:spring-security-config:6.5.3'
    implementation 'org.springframework.security:spring-security-web:6.5.3'

    implementation "io.jsonwebtoken:jjwt-impl:0.12.6"
    implementation "io.jsonwebtoken:jjwt-jackson:0.12.6"


//    implementation("io.jsonwebtoken:jjwt-api:0.12.6")
//    implementation("io.jsonwebtoken:jjwt-impl:0.12.6")
//    implementation("io.jsonwebtoken:jjwt-jackson:0.12.6")

    //email
//    implementation group: 'javax.mail', name: 'javax.mail-api', version: '1.6.2'
//    implementation group: 'javax.mail', name: 'mail', version: '1.4.7'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.thymeleaf:thymeleaf:3.0.11.RELEASE'
    implementation 'org.thymeleaf:thymeleaf-spring5:3.0.11.RELEASE'


    implementation group: 'commons-io', name: 'commons-io', version: '2.18.0'

    implementation group:'org.apache.commons', name:'commons-lang3', version:'3.17.0'
    implementation group:'org.apache.commons',name:'commons-collections4',version:'4.5.0'

    // mobile authentication - firebase
    implementation group: 'com.google.firebase', name: 'firebase-admin', version: '9.1.1'



    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //junit test
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    //jdbc
    implementation group: 'org.springframework', name: 'spring-jdbc', version: '6.2.0'

    //data base
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.7.4'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    //entity
    implementation 'jakarta.json:jakarta.json-api:2.1.1'
//    implementation group: 'jakarta.persistence', name: 'jakarta.persistence-api', version: '3.2.0'


}
//
//tasks.named('test') {
//    useJUnitPlatform()
//}
